Repository pixel-museum/css-art-museum, pull requests merged in 2025-10, with the labels that each got.

#52 Added 4 loading animations
  arts/dot-loading.html
  arts/dot-wave-loading.html
  arts/matrix-pulse-loading.html
  arts/ring-loading.html
  index.html
Labels: enhancement, hacktoberfest 2025

#62 My artwork
  arts/hariksh-sunset.html
  index.html
Labels: enhancement, hacktoberfest 2025

#69 Add new CSS art: bouncing ball, floating orb, pulsating ring, waves
  arts/bouncing_ball.html
  arts/floating_orb.html
  arts/pulsating_ring.html
  arts/waves.html
  index.html
Labels: enhancement, hacktoberfest 2025, hacktoberfest-accepted

#73 Add Hovering UFO CSS Art
  arts/angel-ufo_alien.html
  index.html
Labels: enhancement, hacktoberfest 2025

#70 Added CSS artwork: Aurora by Manu Dwivedi
  arts/manudwivedi-aurora.html
  index.html
Labels: enhancement, hacktoberfest 2025, hacktoberfest-accepted

#39 Added CSS flower art and updated styles
  arts/sarab-cssflower.html
  index.html
Labels: enhancement, hacktoberfest 2025, hacktoberfest-accepted

#95 Dark mode fix across website
  art-viewer.html
  script.js
Labels: enhancement, hacktoberfest 2025, hacktoberfest-accepted

#84 Added CSS artwork: Face by Pratik
  arts.json
  arts/pratik_face.html
  index.html
Labels: enhancement, hacktoberfest 2025, hacktoberfest-accepted

#106 Added two new ArtWork on Curosity Theme
  arts.json
  arts/celestial_engine.html
  arts/morphin_art.html
Labels: hacktoberfest-accepted

#111 animated card added
  arts.json
  arts/Soumyosish_animated_gradient_card.html
Labels: hacktoberfest 2025

#101 Rotating Earth & Moon CSS Artwork by Pratham
  arts.json
  arts/prath-rotating-earth.html
Labels: enhancement, hacktoberfest-accepted

#121 Added CSS artwork : Celestial Wanderers by Aerospace
  arts.json
  arts/aerospace-celestial_wanderers.html
  index.html
Labels: hacktoberfest-accepted

#127 Add interactive homepage with navbar and gradient title
  favconicon.png
  gallery.html
  index.html
  style.css
Labels: hacktoberfest 2025, hacktoberfest-accepted

#126 Added CSS artwork: Injora-Glowing_Dusk
  arts.json
  arts/glowing_dusk.html
Labels: enhancement, hacktoberfest 2025, hacktoberfest-accepted

#129 Added Gravity Affected ball Card
  arts.json
  arts/gravity-affected-ball.html
  style.css
Labels: hacktoberfest-accepted

#134 Added Peacock and Hacker artwork
  arts.json
  arts/ujjwal-hacker.html
  arts/ujjwal-peacock.html
Labels: hacktoberfest-accepted

#149 Added my artwork Arc reactor
  arts.json
  arts/Waqar-arc.html
Labels: hacktoberfest-accepted

#150 Added CSS artwork: Soham-Scenery
  arts.json
  arts/scenery.html
Labels: hacktoberfest 2025, hacktoberfest-accepted

#151 Added CSS artwork: Cosmic Orb
  arts.json
  arts/rajat-cosmic-orb.html
Labels: hacktoberfest-accepted

#116 Noor’s Space Art
  arts/noor-spaceart.html
  index.html
Labels: hacktoberfest-accepted

#165 Added CSS artwork: Neon City by Anuradha
  arts.json
  arts/Anuradha-neon-city.html
Labels: hacktoberfest-accepted

#171 Feature : Add recently viewed art #164
  index.html
  js/script.js
  style.css
Labels: hacktoberfest 2025, hacktoberfest-accepted

#205 Fix: Sort by likes now works on filtered search results
  js/script.js
Labels: hacktoberfest 2025, hacktoberfest-accepted

#198 Light House By the Shore CSS Animation
  arts.json
  arts/lighthouse.html
Labels: hacktoberfest-accepted

#197 feat: Add Matrix Terminal Loader artwork by Krasper707
  Contributors/contributors.json
  arts.json
  arts/Krasper707-matrix-background.html
Labels: hacktoberfest-accepted
